apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-app
  namespace: argocd
spec:
  destination:
    namespace: test-helm-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kafka
    repoURL: https://albertollamaso.github.io/kafka-chart
    targetRevision: 14.4.1
    helm:
      releaseName: kafka-app-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true